/** @type {import('orval').Options} */
export default {
  pathsApi: {
    input: './schema/openapi.json',
    output: {
      client: 'vue-query',
      target: './src/generated/apiClient.ts',
      schemas: './src/generated/types',
      mode: 'single',
      override: {
        // Default header includes "OpenAPI spec version: X", which touches every
        // generated file's header on any backend version bump even when that
        // file's actual content didn't change. Drop it to keep diffs meaningful.
        header: ({ title, description }) => [
          'Generated by orval 🍺',
          'Do not edit manually.',
          ...(title ? [title] : []),
          ...(description ? [description] : []),
        ],
        mutator: {
          path: './src/lib/customFetch.ts',
          name: 'customFetch',
        },
      },
    },
  },
};
