/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/callback': RouteRecordInfo<
      '/auth/callback',
      '/auth/callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/delete': RouteRecordInfo<
      '/delete',
      '/delete',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/entry/[pathId]/[entryId]/': RouteRecordInfo<
      '/entry/[pathId]/[entryId]/',
      '/entry/:pathId/:entryId',
      { pathId: ParamValue<true>, entryId: ParamValue<true> },
      { pathId: ParamValue<false>, entryId: ParamValue<false> },
      | never
    >,
    '/entry/[pathId]/[entryId]/edit': RouteRecordInfo<
      '/entry/[pathId]/[entryId]/edit',
      '/entry/:pathId/:entryId/edit',
      { pathId: ParamValue<true>, entryId: ParamValue<true> },
      { pathId: ParamValue<false>, entryId: ParamValue<false> },
      | never
    >,
    '/entry/new': RouteRecordInfo<
      '/entry/new',
      '/entry/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/export': RouteRecordInfo<
      '/export',
      '/export',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/invitations': RouteRecordInfo<
      '/invitations',
      '/invitations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/auth/callback.vue': {
      routes:
        | '/auth/callback'
      views:
        | never
    }
    'src/pages/delete.vue': {
      routes:
        | '/delete'
      views:
        | never
    }
    'src/pages/entry/[pathId]/[entryId]/index.vue': {
      routes:
        | '/entry/[pathId]/[entryId]/'
      views:
        | never
    }
    'src/pages/entry/[pathId]/[entryId]/edit.vue': {
      routes:
        | '/entry/[pathId]/[entryId]/edit'
      views:
        | never
    }
    'src/pages/entry/new.vue': {
      routes:
        | '/entry/new'
      views:
        | never
    }
    'src/pages/export.vue': {
      routes:
        | '/export'
      views:
        | never
    }
    'src/pages/invitations.vue': {
      routes:
        | '/invitations'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
